//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling search process....
        /// </summary>
        internal static string MainWindow_buttonCancel_Click_Cancelling_search_process_message {
            get {
                return ResourceManager.GetString("MainWindow_buttonCancel_Click_Cancelling_search_process_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files satisfying the conditions were found!.
        /// </summary>
        internal static string MainWindow_buttonSearch_Click_No_files_found_message {
            get {
                return ResourceManager.GetString("MainWindow_buttonSearch_Click_No_files_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search process canceled!.
        /// </summary>
        internal static string MainWindow_buttonSearch_Click_Search_process_canceled_message {
            get {
                return ResourceManager.GetString("MainWindow_buttonSearch_Click_Search_process_canceled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search process finished!.
        /// </summary>
        internal static string MainWindow_buttonSearch_Click_Search_process_finished_message {
            get {
                return ResourceManager.GetString("MainWindow_buttonSearch_Click_Search_process_finished_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search process started!.
        /// </summary>
        internal static string MainWindow_buttonSearch_Click_Search_process_start_message {
            get {
                return ResourceManager.GetString("MainWindow_buttonSearch_Click_Search_process_start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened file: .
        /// </summary>
        internal static string MainWindow_listBoxSearchResults_MouseDoubleClick_Open_file_message {
            get {
                return ResourceManager.GetString("MainWindow_listBoxSearchResults_MouseDoubleClick_Open_file_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found file: .
        /// </summary>
        internal static string MainWindow_ManageNewFoundFile_Found_file_message {
            get {
                return ResourceManager.GetString("MainWindow_ManageNewFoundFile_Found_file_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string MainWindow_ManageNewFoundFile_Too_long_string_symbols {
            get {
                return ResourceManager.GetString("MainWindow_ManageNewFoundFile_Too_long_string_symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with directory: .
        /// </summary>
        internal static string SearchEngine_Find_Error_directory_message {
            get {
                return ResourceManager.GetString("SearchEngine_Find_Error_directory_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with processing file: .
        /// </summary>
        internal static string SearchEngine_Find_Error_processing_file_message {
            get {
                return ResourceManager.GetString("SearchEngine_Find_Error_processing_file_message", resourceCulture);
            }
        }
    }
}
